### ISSUE TITLE
Enable mouse scroll wheel (CircularAxisInput) to rotate the simulated controllers in the local Z axis.

### ISSUE THREAD

**Issue by hawkwood** [ExtendRealityLtd/Tilia.CameraRigs.SpatialSimulator.Unity#101]
The ability to rotate the simulated controllers in the local Z axis
will make the simulator more useful for testing when physical 
hardware is not available.

**Comment by hawkwood** [comment]
Solution: [https://github.com/ExtendRealityLtd/Tilia.CameraRigs.SpatialSimulator.Unity/pull/102](https://github.com/ExtendRealityLtd/Tilia.CameraRigs.SpatialSimulator.Unity/pull/102)

**Comment by thestonefox** [comment]
I like the solution in concept. but sometimes i use the mouse wheel for other rotations such as rotating the cursor on a pointer (simulating touchpad angles)

so should this solution include a hotkey to enable/disable this rotation on a controller? or does it only activate when controlling the controller object within the simulator? If so, then that's enough I think

**Comment by hawkwood** [comment]
This uses the same switching methodology as the existing system, so it is only activate when a specific controller is being controlled by the mouse.

**Comment by thestonefox** [comment]
That's ideal then, so if i'm not controlling the controller model then i can use the mouse wheel for something else. Good addition 👍
